/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Story = IDL.Record({
  'id' : IDL.Int,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Time,
});
export const VolunteerApplication = IDL.Record({
  'areaOfExpertise' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'motivation' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Int,
  'content' : IDL.Text,
  'storyId' : IDL.Int,
  'authorName' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteComment' : IDL.Func([IDL.Int], [], []),
  'deleteStory' : IDL.Func([IDL.Int], [], []),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllVolunteerApplications' : IDL.Func(
      [],
      [IDL.Vec(VolunteerApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByStory' : IDL.Func([IDL.Int], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postComment' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [IDL.Int], []),
  'postStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Int], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitVolunteerApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Story = IDL.Record({
    'id' : IDL.Int,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Time,
  });
  const VolunteerApplication = IDL.Record({
    'areaOfExpertise' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'motivation' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Int,
    'content' : IDL.Text,
    'storyId' : IDL.Int,
    'authorName' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteComment' : IDL.Func([IDL.Int], [], []),
    'deleteStory' : IDL.Func([IDL.Int], [], []),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllVolunteerApplications' : IDL.Func(
        [],
        [IDL.Vec(VolunteerApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByStory' : IDL.Func([IDL.Int], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postComment' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [IDL.Int], []),
    'postStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Int], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitVolunteerApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };